name: Build Windows CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Download atif
        run: curl -o ./bin/AtifExe.exe https://github.com/valbendan/Atif/releases/download/v1.0.3/AtifExe.exe

      - run: yarn install

      - run: yarn package

      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: out
